language: python
python:
  - "3.6"      # current default Python on Travis CI
# command to install dependencies
before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.11.1/geckodriver-v0.11.1-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.11.1-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
install:
  - pip3 install -r requirements.txt
# command to run tests
script:
  - cd pawnshop_crm
  - python3 manage.py migrate
  - pytest -vvv
