version: '3'

services:
  django:
    image: docker.pkg.github.com/glokzs/lombard_crm/lombard_crm
    command: bash -c 'python3 pawnshop_crm/manage.py collectstatic --noinput && python3 pawnshop_crm/manage.py migrate && cd pawnshop_crm && gunicorn -c gunicorn.conf pawnshop_crm.wsgi'
    volumes:
      - ./gunicorn.conf:/src/pawnshop_crm/gunicorn.conf
      - ./static:/src/pawnshop_crm/static
    ports:
      - 8000:8000

  nginx:
    image: nginx:latest
    depends_on:
      - django
    environment:
      - TZ=Asia/Almaty
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static:/static
    ports:
      - "80:80"
      - "443:443"